---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Provision a Jenkins instance
      ec2:
         key_name: jenkins-key
         group: Jenkins
         instance_type: t2.micro
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         image: "{{ ami_id }}"
         wait: true
         region: us-east-2
         vpc_subnet_id: subnet-45566a2d
         assign_public_ip: yes
         termination_protection: yes
         exact_count: 1
         count_tag:
            Name: Jenkins-Master
         instance_tags:
            Name: Jenkins-Master
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      with_items: "{{ ec2.instances }}"
